/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_alexis_jpicotts_PicoTTS */

#ifndef _Included_org_alexis_jpicotts_PicoTTS
#define _Included_org_alexis_jpicotts_PicoTTS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_alexis_jpicotts_PicoTTS
 * Method:    setup
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_alexis_jpicotts_PicoTTS_setup
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_alexis_jpicotts_PicoTTS
 * Method:    say
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_alexis_jpicotts_PicoTTS_say
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
